# Generated by Django 4.2.4 on 2023-09-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshareapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guser',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
    ]
